# Generated by Django 5.1.5 on 2025-01-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
